apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels: 
    app: canvas
    type: backend

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: canvas
      
  template:
    metadata:
      labels: 
        app: canvas
    spec:
      containers:
      - name: canvas
        image: upanshu21/canvas-app:latest
        ports: 
        - containerPort: 8000
        # resources:
        #   limits: 
        #     memory: "216Mi"
        #     cpu: "400m"
        env:
        - name: MONGO_HOST
          value: "10.244.0.33"
        - name: MONGO_ROOT_USER
          value: root
        - name: MONGO_ROOT_PASSWORD
          value: hunter2
        - name: MONGO_DB_NAME
          value: trauplin
        - name: MONGO_AUTH_SOURCE
          value: admin
          
