apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels: 
    app: mongodb
    type: db

spec:
  selector: 
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: hunter2
        - name: MONGO_USER
          value: trauplin
        - name: MONGO_PASSWORD
          value: hunter2
        - name: MONGO_INITDB_DATABASE
          value: trauplin
