apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: yelp-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000


